-- MySQL Script generated by MySQL Workbench
-- Sun 03 May 2026 12:02:07 AM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `street_number` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `address_fk_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `address_persons_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT NOT NULL,
  `branch_id` INT NULL,
  `position` VARCHAR(50) NULL,
  `salary` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `persons_employees_fk`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manager_id` INT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `manager_fk_idx` (`manager_id` ASC) VISIBLE,
  INDEX `address_fk_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `manager_fk`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address_branch_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NULL,
  `address_id` INT NOT NULL,
  `size` INT NULL,
  `type` VARCHAR(45) NULL,
  `employee_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `branch_fk_idx` (`branch_id` ASC) VISIBLE,
  INDEX `employee_fk_idx` (`employee_id` ASC) VISIBLE,
  INDEX `address_fk_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `branch_property_fk`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_property_fk`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address_property_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rental_listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rental_listing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `property_fk_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `property_rental_listing_fk`
    FOREIGN KEY (`property_id`)
    REFERENCES `mydb`.`properties` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newspaper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newspaper` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listing_newspaper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listing_newspaper` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing_id` INT NOT NULL,
  `newspaper_id` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `listing_fk_idx` (`listing_id` ASC) VISIBLE,
  INDEX `newspaper_fk_idx` (`newspaper_id` ASC) VISIBLE,
  CONSTRAINT `rental_listing_fk`
    FOREIGN KEY (`listing_id`)
    REFERENCES `mydb`.`rental_listing` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `newspaper_rental_listing_fk`
    FOREIGN KEY (`newspaper_id`)
    REFERENCES `mydb`.`newspaper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tenants` (
  `id` INT NOT NULL,
  `branch_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `branch_fk_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `branch_tenants_fk`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `persons_tenants_fk`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owners` (
  `id` INT NOT NULL,
  `type` ENUM('person', 'company') NOT NULL,
  PRIMARY KEY (`id`, `type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agreements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agreements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `signing_date` DATE NULL,
  `end_date` DATE NULL,
  `owner_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `property_id` INT NOT NULL,
  `owner_type` ENUM('person', 'company') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `property_fk_idx` (`property_id` ASC) VISIBLE,
  INDEX `tenant_fk_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `owner_fk_idx` (`owner_id` ASC, `owner_type` ASC) VISIBLE,
  CONSTRAINT `property_agreements_fk`
    FOREIGN KEY (`property_id`)
    REFERENCES `mydb`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tenant_agreements_fk`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `mydb`.`tenants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner_agreements_fk`
    FOREIGN KEY (`owner_id` , `owner_type`)
    REFERENCES `mydb`.`owners` (`id` , `type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viewings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viewings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `tenants_fk_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `property_fk_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `tenants_viewings_fk`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `mydb`.`tenants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `property_viewings_fk`
    FOREIGN KEY (`property_id`)
    REFERENCES `mydb`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone_numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(45) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `persons_phone_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`email_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`email_addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `email_address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `persons_email_fk`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`property_ownership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`property_ownership` (
  `property_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `owner_type` ENUM('person', 'company') NOT NULL,
  INDEX `property_fk_idx` (`property_id` ASC) VISIBLE,
  INDEX `owner_fk_idx` (`owner_id` ASC, `owner_type` ASC) VISIBLE,
  PRIMARY KEY (`property_id`, `owner_id`, `owner_type`),
  CONSTRAINT `property_ownership_fk`
    FOREIGN KEY (`property_id`)
    REFERENCES `mydb`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `owner_ownership_fk`
    FOREIGN KEY (`owner_id` , `owner_type`)
    REFERENCES `mydb`.`owners` (`id` , `type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `address_company_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch_phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch_phone_numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `branch_fk_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `branch_phone_fk`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`branch_emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`branch_emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `email_address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `branch_fk_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `branch_email_fk`
    FOREIGN KEY (`branch_id`)
    REFERENCES `mydb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_phone_numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `company_fk_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `company_phone_fk`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `email_address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `company_fk_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `company_email_fk`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
